name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup Replicate Cog
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
          
      # Build and push the model to Replicate
      - name: Push to Replicate
        run: cog push r8.im/nutshellagency/omnitry-vton
